version: '3.7'

services:
  mariadb:
    image: mariadb:10.5.4
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_USER=mariadb
      - MYSQL_DATABASE=nextcloud
      - MYSQL_PASSWORD=mariadb
    volumes:
      - mariadb:/var/lib/postgresql/data
      - backups:/backups
    deploy:
      placement:
        constraints:
          - node.labels.tipo == teste
#     resources:
#        limits:
#          memory: 256M
#          cpus: '0.5'

  nextcloud:
    image: akirax/nextcloud
    depends_on:
      - mariadb
      - redis
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_DB=nextcloud
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=mariadb
      - NEXTCLOUD_ADMIN=admin
      - NEXTCLOUD_ADMIN_USER=admin
      - REDIS_HOST=redis
    ports:
      - 8076:80
    volumes:
      - nextcloud:/var/www/html
    deploy:
      placement:
        constraints:
          - node.labels.tipo == teste
#      resources:
#        limits:
#          memory: 256M
#          cpus: '0.5'

  redis:
    image: redis:alpine
    environment:
      - REDIS_DATABASES=1
    deploy:
      placement:
        constraints:
          - node.labels.tipo == teste
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

volumes:
  mariadb:
    driver_opts:
      o: bind
      type: none
      device: /data/nextcloud/mariadb
  backups:
    driver_opts:
      o: bind
      type: none
      device: /data/nextcloud/backups
  nextcloud:
    driver_opts:
      o: bind
      type: none
      device: /data/nextcloud/nextcloud
