version: '3.7'

services:
  mariadb:
    image: mariadb:10.5.4
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_USER=mariadb
      - MYSQL_DATABASE=nextcloud
      - MYSQL_PASSWORD=mariadb
    volumes:
      - mariadb:/var/lib/mysql
      - backups:/backups
    deploy:
     resources:
       limits:
         memory: 512M
         cpus: '0.5'

  nextcloud:
    image: akirax/nextcloud
    depends_on:
      - mariadb
      - redis
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=mariadb
      - NEXTCLOUD_ADMIN=admin
      - NEXTCLOUD_ADMIN_USER=admin
      - REDIS_HOST=redis
    ports:
      - 8076:80
    volumes:
      - nextcloud:/var/www/html
      - datanextcloud:/data
    deploy:
      resources:
        limits:
          memory: 800M
          cpus: '0.5'

  redis:
    image: redis:alpine
    environment:
      - REDIS_DATABASES=1
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '0.5'

volumes:
  mariadb:
    driver_opts:
      o: bind
      type: none
      device: /data/nextcloud/mariadb
  backups:
    driver_opts:
      o: bind
      type: none
      device: /data/nextcloud/backups
  nextcloud:
    driver_opts:
      o: bind
      type: none
      device: /data/nextcloud/nextcloud
  datanextcloud:
    driver_opts:
      o: bind
      type: none
      device: /mnt/nuvem/nuvem/owncloud/data
